# Generated by Django 3.2.22 on 2024-08-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastos',
            name='repeticao',
        ),
        migrations.AddField(
            model_name='gastos',
            name='parcelas',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
