# Generated by Django 3.2.22 on 2024-08-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_auto_20240806_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='tipoPagamento',
            field=models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
