# Generated by Django 3.2.22 on 2024-08-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aparencia_tela', models.CharField(blank=True, choices=[('C', 'Claro'), ('E', 'Escuro')], default='C', max_length=1, null=True)),
                ('notificacaoRecebimentos', models.BooleanField(default=True)),
                ('diasNotificacaoReceb', models.IntegerField(default=1)),
                ('notificacaoGastos', models.BooleanField(default=True)),
                ('diasNotificacaoGastos', models.CharField(blank=True, choices=[('1', 'Uma vez por dia'), ('2', 'A cada dois dias'), ('3', 'Uma vez por semana'), ('4', 'Uma vez a cada duas semanas'), ('5', 'Uma vez a cada quinzena'), ('6', 'Uma vez por mês')], default='1', max_length=1, null=True)),
                ('notificacaoContas', models.BooleanField(default=True)),
                ('diasNotificacaoContas', models.IntegerField(default=1)),
            ],
        ),
    ]
