# Generated by Django 3.2.22 on 2024-08-08 23:28

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoPerfil', models.ImageField(blank=True, null=True, upload_to='fotosPerfil/', validators=[usuario.models.tamanho_img])),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
